import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0B0F19" },
  center: { justifyContent: "center", alignItems: "center" },
  loadingText: {
    color: "#94A3B8",
    marginTop: 12,
    fontSize: 13,
    fontWeight: "500",
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  backBtn: {
    marginRight: 14,
    padding: 8,
    backgroundColor: "#1E293B",
    borderRadius: 10,
  },
  headerTitleContainer: { flex: 1 },
  headerTitle: { color: "#F8FAFC", fontSize: 18, fontWeight: "700" },
  headerSubtitle: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },

  overviewCard: {
    backgroundColor: "#111827",
    margin: 16,
    marginBottom: 8,
    padding: 18,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  overviewLabel: { color: "#94A3B8", fontSize: 12, fontWeight: "600" },
  overviewAmount: {
    color: "#F8FAFC",
    fontSize: 24,
    fontWeight: "800",
    marginTop: 2,
  },
  overviewBadge: {
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  overviewBadgeText: { color: "#38BDF8", fontSize: 11, fontWeight: "700" },

  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#111827",
    padding: 4,
    marginHorizontal: 16,
    marginVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  tabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 9,
    gap: 6,
  },
  tabActive: {
    backgroundColor: "#1F2937",
  },
  tabText: { color: "#64748B", fontSize: 12, fontWeight: "600" },
  tabTextActive: { color: "#F8FAFC", fontWeight: "700" },

  listContainer: { paddingHorizontal: 16, paddingBottom: 30, paddingTop: 4 },
  card: {
    backgroundColor: "#111827",
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  row: { flexDirection: "row", alignItems: "center", flex: 1 },
  iconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  cardTitle: { color: "#F8FAFC", fontSize: 15, fontWeight: "700" },
  cardSub: { color: "#94A3B8", fontSize: 12, marginTop: 2 },
  statusBadgePending: {
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  statusBadgePendingText: { color: "#F59E0B", fontSize: 10, fontWeight: "700" },
  amountText: { color: "#F8FAFC", fontSize: 17, fontWeight: "800" },

  payButton: {
    backgroundColor: "#3B82F6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 14,
  },
  payButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },

  historyDetailsFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    paddingTop: 10,
  },
  remarksText: { color: "#94A3B8", fontSize: 11, flex: 1, marginRight: 10 },
  dateText: { color: "#64748B", fontSize: 11, fontWeight: "600" },

  emptyBox: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyIconBg: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#111827",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  emptyTitle: { color: "#F8FAFC", fontSize: 16, fontWeight: "700" },
  emptyText: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },

  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  modalContent: {
    backgroundColor: "#0F172A",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  modalTitle: { color: "#F8FAFC", fontSize: 18, fontWeight: "700" },
  modalSubTitle: { color: "#94A3B8", fontSize: 12, marginTop: 2 },
  closeBtn: {
    backgroundColor: "#1E293B",
    padding: 6,
    borderRadius: 8,
  },
  inputLabel: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    backgroundColor: "#1E293B",
    borderWidth: 1,
    borderColor: "#334155",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#F8FAFC",
    fontSize: 14,
  },
  submitButton: {
    backgroundColor: "#10B981",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 10,
  },
  submitButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },

  // --- Added New Styles for Payment Options & Receipt Modal ---
  paymentModeContainer: {
    flexDirection: "row",
    marginBottom: 12,
    justifyContent: "space-between",
  },
  paymentModeBtn: {
    flex: 1,
    marginHorizontal: 4,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E293B",
    backgroundColor: "#111827",
    alignItems: "center",
  },
  paymentModeBtnActive: {
    borderColor: "#38BDF8",
    backgroundColor: "rgba(56, 189, 248, 0.15)",
  },
  paymentModeText: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "500",
  },
  paymentModeTextActive: {
    color: "#38BDF8",
    fontWeight: "700",
  },
  receiptOverlay: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  receiptCard: {
    backgroundColor: "#0B0F19",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E293B",
    paddingHorizontal: 20,
    paddingVertical: 22,
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  receiptHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#161E2E",
    paddingBottom: 14,
    marginBottom: 16,
  },
  receiptIconBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "rgba(14, 165, 233, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(14, 165, 233, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  receiptTitle: {
    color: "#F8FAFC",
    fontSize: 15,
    fontWeight: "600",
  },
  receiptSubId: {
    color: "#64748B",
    fontSize: 10,
    marginTop: 1,
  },
  receiptCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 6,
    backgroundColor: "#161E2E",
    justifyContent: "center",
    alignItems: "center",
  },
  receiptInfoBox: {
    backgroundColor: "#111827",
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  receiptAmountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1F2937",
    paddingBottom: 10,
  },
  receiptAmountLabel: { color: "#9CA3AF", fontSize: 12 },
  receiptAmountVal: { color: "#34D399", fontWeight: "700", fontSize: 16 },
  receiptDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  receiptKey: { color: "#6B7280", fontSize: 11 },
  receiptVal: { color: "#F3F4F6", fontSize: 11, fontWeight: "600" },
  previewBtn: {
    backgroundColor: "#0284C7",
    borderRadius: 8,
    height: 42,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  shareBtn: {
    backgroundColor: "#10B981",
    borderRadius: 8,
    height: 42,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  btnTextWhite: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  receiptCloseTextBtn: {
    height: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  receiptCloseText: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
});
