import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0B0F19" },
  loadingCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0B0F19",
  },
  loadingText: { color: "#94A3B8", marginTop: 10, fontSize: 13 },
  header: {
    backgroundColor: "#0F172A",
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#1E293B",
  },
  headerLeft: { flex: 1 },
  welcomeText: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
  tenantName: {
    color: "#F8FAFC",
    fontSize: 20,
    fontWeight: "800",
    marginTop: 2,
  },
  pgBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  pgNameText: { color: "#38BDF8", fontSize: 11, fontWeight: "600" },
  logoutBtn: {
    backgroundColor: "#1E293B",
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#334155",
  },
  scrollContent: { padding: 16, paddingBottom: 30 },
  summaryCard: {
    backgroundColor: "#111827",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "#1F2937",
    marginBottom: 24,
  },
  summaryCardPaid: {
    borderColor: "rgba(52, 211, 153, 0.3)",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardLabel: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  cardValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F8FAFC",
    marginTop: 3,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  statusText: { fontSize: 11, fontWeight: "700" },
  divider: { height: 1, backgroundColor: "#1F2937", marginVertical: 16 },
  rentDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rentAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: "#38BDF8",
    marginTop: 2,
  },
  alignRight: { alignItems: "flex-end" },
  dueDate: { fontSize: 12, fontWeight: "700", color: "#F8FAFC", marginTop: 3 },
  payButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 12,
    height: 46,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 18,
  },
  payButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 6,
  },
  paidSuccessBox: {
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.2)",
  },
  paidSuccessText: { color: "#34D399", fontSize: 12, fontWeight: "600" },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F8FAFC",
    marginBottom: 12,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  gridItem: {
    backgroundColor: "#111827",
    width: "48%",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  iconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  gridTitle: { fontSize: 14, fontWeight: "700", color: "#F8FAFC" },
  gridSub: { fontSize: 11, color: "#94A3B8", marginTop: 2 },
  noticeCard: {
    backgroundColor: "rgba(59, 130, 246, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.2)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  noticeTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#60A5FA",
    marginBottom: 6,
  },
  noticeText: { fontSize: 12, color: "#93C5FD", lineHeight: 18 },
  noticeDate: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 10,
    textAlign: "right",
    fontWeight: "600",
  },
});
