import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerTitle: { fontSize: 17, fontWeight: "bold", color: "#1A1A1A" },
  backButton: { padding: 4 },
  addButtonHeader: {
    backgroundColor: "#06B6D4",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  pgBarContainer: {
    backgroundColor: "#FFF",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  scrollRow: { paddingHorizontal: 16 },
  pgChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    marginRight: 8,
  },
  pgChipActive: { backgroundColor: "#0F172A" },
  commonChip: { borderWidth: 1, borderColor: "#06B6D4", borderStyle: "dashed" },
  pgChipText: { fontSize: 13, fontWeight: "600", color: "#4B5563" },
  pgChipTextActive: { color: "#FFF" },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#FFF",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  tabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    marginHorizontal: 4,
  },
  activeTabButton: {
    backgroundColor: "#ECFEFF",
    borderWidth: 1,
    borderColor: "#06B6D4",
  },
  tabText: { fontSize: 12, fontWeight: "600", color: "#6B7280" },
  activeTabText: { color: "#0E7490", fontWeight: "bold" },
  scrollContent: { padding: 16 },
  banner: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  commonBanner: { backgroundColor: "#0369A1" },
  bannerLabel: {
    color: "#38BDF8",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
    textAlign: "center",
  },
  bannerSubLabel: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  archiveCard: {
    backgroundColor: "#F9FAFB",
    borderColor: "#E5E7EB",
  },
  urgentCard: { borderColor: "#FCA5A5", backgroundColor: "#FEF2F2" },
  cardHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 8,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ECFEFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  archiveIconContainer: {
    backgroundColor: "#F3F4F6",
  },
  urgentIconContainer: { backgroundColor: "#FEE2E2" },
  noticeTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 2,
  },
  noticeCategory: { fontSize: 11, color: "#6B7280" },
  urgentBadge: {
    backgroundColor: "#EF4444",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  urgentText: { color: "#FFF", fontSize: 10, fontWeight: "bold" },
  noticeDesc: { fontSize: 13, color: "#4B5563", lineHeight: 18, marginTop: 4 },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    backgroundColor: "#FFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  emptyText: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  modalHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#1A1A1A" },
  targetPgText: {
    fontSize: 12,
    color: "#4B5563",
    marginBottom: 14,
    backgroundColor: "#F0FDF4",
    padding: 8,
    borderRadius: 6,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#1A1A1A",
    marginBottom: 12,
    backgroundColor: "#F9FAFB",
  },
  textArea: { height: 90, textAlignVertical: "top" },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  switchLabel: { fontSize: 13, fontWeight: "bold", color: "#1F2937" },
  switchSub: { fontSize: 11, color: "#6B7280" },
  saveBtn: {
    backgroundColor: "#06B6D4",
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginTop: 6,
  },
  saveBtnText: { color: "#FFF", fontWeight: "bold", fontSize: 15 },
});
