import { COLORS, RADIUS, SPACING } from "@/src/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  contentWrapper: {
    flex: 1,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.sm,
  },
  brandTitle: {
    color: COLORS.accent,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  title: { color: COLORS.textPrimary, fontSize: 20, fontWeight: "700" },
  monthPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  monthPillText: { color: COLORS.accent, fontSize: 13, fontWeight: "600" },
  pgFilterDropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.md,
  },
  pgFilterLabel: { color: COLORS.textSecondary, fontSize: 13, flex: 1 },
  analyticsCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.xs,
  },
  analyticsTitle: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  progressPercent: { color: COLORS.accent, fontSize: 13, fontWeight: "700" },
  progressBarTrack: {
    height: 6,
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.full,
    marginVertical: SPACING.md,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: COLORS.success,
    borderRadius: RADIUS.full,
  },
  metricGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: SPACING.xs,
  },
  metricLabel: {
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  metricValue: { fontSize: 16, fontWeight: "700", marginTop: 2 },
  metricDivider: { width: 1, height: 24, backgroundColor: COLORS.border },
  filterSection: { marginBottom: SPACING.md },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    height: 42,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.sm,
  },
  searchInput: { flex: 1, color: COLORS.textPrimary, fontSize: 14 },
  segmentedControl: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    padding: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: SPACING.xs,
    alignItems: "center",
    borderRadius: RADIUS.md,
  },
  segmentBtnActive: { backgroundColor: COLORS.cardBg },
  segmentText: { color: COLORS.textMuted, fontSize: 12, fontWeight: "600" },
  segmentTextActive: { color: COLORS.textPrimary, fontWeight: "700" },
  tenantCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: SPACING.sm,
  },
  flatTagContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    marginRight: SPACING.sm,
  },
  flatNumberTag: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.accent,
    maxWidth: 140,
  },
  flatNumberText: { color: COLORS.accent, fontSize: 10, fontWeight: "800" },
  apartmentNameTag: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    maxWidth: 180,
  },
  apartmentNameText: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontWeight: "600",
  },
  remindIconBtn: {
    backgroundColor: COLORS.surface,
    padding: 4,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.full,
  },
  paidBadge: { backgroundColor: "rgba(16, 185, 129, 0.1)" },
  partialBadge: { backgroundColor: "rgba(59, 130, 246, 0.1)" },
  dueBadge: { backgroundColor: "rgba(245, 158, 11, 0.1)" },
  statusDot: { width: 6, height: 6, borderRadius: 3, marginRight: 4 },
  paidDot: { backgroundColor: COLORS.success },
  partialDot: { backgroundColor: "#3B82F6" },
  dueDot: { backgroundColor: COLORS.warning },
  statusText: { fontSize: 11, fontWeight: "700" },
  paidText: { color: COLORS.successText },
  partialText: { color: "#3B82F6" },
  dueText: { color: COLORS.warningText },
  cardBody: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  tenantName: { color: COLORS.textPrimary, fontSize: 16, fontWeight: "700" },
  historyLinkText: {
    color: COLORS.accent,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 4,
  },
  actionPayBtn: {
    backgroundColor: COLORS.success,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  actionPayBtnText: {
    color: COLORS.textWhite,
    fontSize: 12,
    fontWeight: "700",
  },
  completedPill: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  completedPillText: {
    color: COLORS.successText,
    fontSize: 12,
    fontWeight: "700",
  },
  emptyCard: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.xxl,
  },
  emptyTitle: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "700",
    marginTop: SPACING.sm,
  },
  emptySub: {
    color: COLORS.textMuted,
    fontSize: 12,
    textAlign: "center",
    marginTop: 4,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: SPACING.lg,
  },
  modalBox: {
    backgroundColor: COLORS.cardBg,
    width: "100%",
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  historyModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: SPACING.md,
  },
  modalHeaderTitle: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  modalHeaderSub: { color: COLORS.textMuted, fontSize: 12, marginTop: 2 },
  closeIconBtn: { padding: 4 },
  historyCardItem: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  confirmDetailsBox: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.lg,
  },
  confirmRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACING.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  confirmLabel: { color: COLORS.textSecondary, fontSize: 13 },
  confirmValue: {
    color: COLORS.textPrimary,
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
    marginLeft: SPACING.sm,
  },
  modalActionRow: { flexDirection: "row", gap: SPACING.md },
  cancelModalBtn: {
    flex: 1,
    backgroundColor: COLORS.surface,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cancelModalBtnText: {
    color: COLORS.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  confirmModalBtn: {
    flex: 1,
    backgroundColor: COLORS.success,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmModalBtnText: {
    color: COLORS.textWhite,
    fontSize: 13,
    fontWeight: "700",
  },
  contactOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  monthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  monthRowActive: { backgroundColor: COLORS.surface },
  monthRowText: {
    color: COLORS.textMuted,
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
    marginRight: SPACING.sm,
  },
  monthRowTextActive: { color: COLORS.accent, fontWeight: "700" },
});
