import { StyleSheet } from "react-native";
// src/styles/adminUtilitiesStyles.ts
import { COLORS, RADIUS, SPACING } from "../../constants/theme";
import { commonStyles } from "../commonStyles";

export const styles = StyleSheet.create({
  container: commonStyles.container,

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  separatePgCard: {
    backgroundColor: COLORS.background, // Or any custom color/border you want for separate PGs
    borderColor: COLORS.primary, // Highlights it when a specific PG is selected
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardSeparate: {
    backgroundColor: COLORS.background, // Uses theme background instead of hardcoded hex
  },
  separatePgBanner: {
    backgroundColor: "#0369A1", // Distinct color when viewing a separate PG
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  backButton: { padding: 4 },
  addButtonHeader: {
    backgroundColor: COLORS.primary,
    width: 32,
    height: 32,
    borderRadius: RADIUS.full,
    justifyContent: "center",
    alignItems: "center",
  },
  pgBarContainer: {
    backgroundColor: COLORS.surface,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  monthBarContainer: {
    backgroundColor: COLORS.surface,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  scrollRow: { paddingHorizontal: SPACING.lg },

  // FIXED: Active PG chip background should use primary brand color or distinct active contrast
  pgChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.background,
    marginRight: SPACING.sm,
  },
  pgChipActive: {
    backgroundColor: COLORS.primary, // Changed from textPrimary so it highlights cleanly with brand color
  },
  commonChip: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderStyle: "dashed",
  },
  pgChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  pgChipTextActive: { color: COLORS.textWhite },

  monthChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs + 2,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.background,
    marginRight: SPACING.xs,
  },
  monthChipActive: { backgroundColor: COLORS.primary },
  monthChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  monthChipTextActive: { color: COLORS.textWhite },
  scrollContent: { padding: SPACING.lg },

  // Banner states for All PGs vs Separate PG
  banner: {
    backgroundColor: COLORS.surface, // Base style for separate PG
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    alignItems: "center",
    marginBottom: SPACING.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 3,
  },
  commonBanner: { 
    backgroundColor: "#0369A1" // Keeps the custom look for "All PGs (Common)"
  },
  bannerLabel: {
    color: "#38BDF8",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 2,
  },
  bannerSubLabel: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: "500",
  },
  bannerAmount: {
    color: COLORS.textWhite,
    fontSize: 30,
    fontWeight: "bold",
    marginVertical: SPACING.xs,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
  },

  cardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: SPACING.sm,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.full,
    backgroundColor: "#ECFEFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.md,
  },
  expenseTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  expenseCategory: { fontSize: 11, color: COLORS.textSecondary },
  branchSubTag: {
    fontSize: 10,
    color: COLORS.primary,
    fontWeight: "600",
    marginTop: 2,
  },
  cardRight: { alignItems: "flex-end" },
  expenseAmount: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#EF4444",
    marginBottom: 4,
  },
  receiptBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DEF7EC",
    paddingHorizontal: SPACING.xs,
    paddingVertical: 2,
    borderRadius: 4,
  },
  receiptBadgeText: { fontSize: 9, fontWeight: "bold", color: "#03543F" },
  noReceiptText: { fontSize: 10, color: COLORS.textSecondary },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.xl * 1.5,
  },
  emptyText: {
    color: COLORS.textSecondary,
    fontSize: 13,
    marginTop: SPACING.sm,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    elevation: 6,
  },
  modalHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.sm,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  targetPgText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginBottom: SPACING.md,
    backgroundColor: "#F0FDF4",
    padding: SPACING.sm,
    borderRadius: RADIUS.sm,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  input: {
    ...commonStyles.input,
    marginBottom: SPACING.md,
  },
  categoryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: SPACING.md,
  },
  catChip: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs + 2,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.background,
    marginRight: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  catChipActive: { backgroundColor: COLORS.primary },
  catChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  catChipTextActive: { color: COLORS.textWhite },
  uploadBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: "dashed",
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    backgroundColor: COLORS.background,
    marginBottom: SPACING.lg,
  },
  uploadText: { fontSize: 13, color: COLORS.textSecondary, flex: 1 },
  saveBtn: {
    ...commonStyles.primaryButton,
    borderRadius: RADIUS.md,
  },
  saveBtnText: { ...commonStyles.primaryButtonText },
  detailContainer: {
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginVertical: SPACING.md,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: SPACING.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  detailValue: {
    fontSize: 12,
    fontWeight: "500",
    color: COLORS.textPrimary,
    maxWidth: "60%",
    textAlign: "right",
  },
  viewAttachmentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFEFF",
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    marginBottom: SPACING.md,
  },
  viewAttachmentText: {
    color: COLORS.primary,
    fontWeight: "bold",
    fontSize: 13,
  },
  actionButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SPACING.xs,
  },
  closeDetailBtn: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    alignItems: "center",
    marginRight: SPACING.xs,
  },
  closeDetailText: {
    color: COLORS.textSecondary,
    fontWeight: "bold",
    fontSize: 14,
  },
  deleteActionBtn: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#EF4444",
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: SPACING.xs,
  },
  deleteActionText: { color: "#FFF", fontWeight: "bold", fontSize: 14 },
});
export const styles_white = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerTitle: { fontSize: 17, fontWeight: "bold", color: "#1A1A1A" },
  backButton: { padding: 4 },
  addButtonHeader: {
    backgroundColor: "#06B6D4",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  pgBarContainer: {
    backgroundColor: "#FFF",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  monthBarContainer: {
    backgroundColor: "#FFF",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  scrollRow: { paddingHorizontal: 16 },
  pgChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    marginRight: 8,
  },
  pgChipActive: { backgroundColor: "#0F172A" },
  commonChip: { borderWidth: 1, borderColor: "#06B6D4", borderStyle: "dashed" },
  pgChipText: { fontSize: 13, fontWeight: "600", color: "#4B5563" },
  pgChipTextActive: { color: "#FFF" },
  monthChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    marginRight: 6,
  },
  monthChipActive: { backgroundColor: "#06B6D4" },
  monthChipText: { fontSize: 12, fontWeight: "600", color: "#4B5563" },
  monthChipTextActive: { color: "#FFF" },
  scrollContent: { padding: 16 },
  banner: {
    backgroundColor: "#0F172A",
    borderRadius: 14,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    elevation: 3,
  },
  commonBanner: { backgroundColor: "#0369A1" },
  bannerLabel: {
    color: "#38BDF8",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 2,
  },
  bannerSubLabel: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
  bannerAmount: {
    color: "#FFF",
    fontSize: 30,
    fontWeight: "bold",
    marginVertical: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginBottom: 12,
  },
  card: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  cardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ECFEFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  expenseTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 2,
  },
  expenseCategory: { fontSize: 11, color: "#6B7280" },
  branchSubTag: {
    fontSize: 10,
    color: "#06B6D4",
    fontWeight: "600",
    marginTop: 2,
  },
  cardRight: { alignItems: "flex-end" },
  expenseAmount: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#EF4444",
    marginBottom: 4,
  },
  receiptBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DEF7EC",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  receiptBadgeText: { fontSize: 9, fontWeight: "bold", color: "#03543F" },
  noReceiptText: { fontSize: 10, color: "#9CA3AF" },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    color: "#9CA3AF",
    fontSize: 13,
    marginTop: 8,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    elevation: 6,
  },
  modalHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#1A1A1A" },
  targetPgText: {
    fontSize: 12,
    color: "#4B5563",
    marginBottom: 14,
    backgroundColor: "#F0FDF4",
    padding: 8,
    borderRadius: 6,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#1A1A1A",
    marginBottom: 14,
    backgroundColor: "#F9FAFB",
  },
  categoryRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 14 },
  catChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#F3F4F6",
    marginRight: 6,
    marginBottom: 6,
  },
  catChipActive: { backgroundColor: "#06B6D4" },
  catChipText: { fontSize: 12, fontWeight: "600", color: "#4B5563" },
  catChipTextActive: { color: "#FFF" },
  uploadBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderStyle: "dashed",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#F9FAFB",
    marginBottom: 16,
  },
  uploadText: { fontSize: 13, color: "#4B5563", flex: 1 },
  saveBtn: {
    backgroundColor: "#06B6D4",
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
  },
  saveBtnText: { color: "#FFF", fontWeight: "bold", fontSize: 15 },
  detailContainer: {
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    padding: 12,
    marginVertical: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  detailLabel: { fontSize: 12, fontWeight: "600", color: "#6B7280" },
  detailValue: {
    fontSize: 12,
    fontWeight: "500",
    color: "#1F2937",
    maxWidth: "60%",
    textAlign: "right",
  },
  viewAttachmentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFEFF",
    borderWidth: 1,
    borderColor: "#06B6D4",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  viewAttachmentText: { color: "#06B6D4", fontWeight: "bold", fontSize: 13 },
  actionButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  closeDetailBtn: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
    marginRight: 8,
  },
  closeDetailText: { color: "#4B5563", fontWeight: "bold", fontSize: 14 },
  deleteActionBtn: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#EF4444",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  deleteActionText: { color: "#FFF", fontWeight: "bold", fontSize: 14 },
});
