import Ionicons from "@expo/vector-icons/Ionicons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import { router } from "expo-router";
import * as Sharing from "expo-sharing";
import React, { useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Modal,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
export default function Profile() {
  const [isReportModalVisible, setIsReportModalVisible] = useState(false);
  const [selectedReportType, setSelectedReportType] = useState<
    "rent" | "expense" | "tenants"
  >("rent");

  const [selectedMonth, setSelectedMonth] = useState("August 2026");
  const [selectedBranch, setSelectedBranch] = useState(
    "Kunal PG - Main Branch",
  );
  const [isGenerating, setIsGenerating] = useState(false);

  const monthsList = ["August 2026", "July 2026", "June 2026", "May 2026"];
  const branchList = ["Kunal PG - Main Branch", "Kunal PG - Annex Branch"];

  const logout = async () => {
    Alert.alert("Logout", "Kya aap sach mein logout karna chahte hain?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Logout",
        style: "destructive",
        onPress: async () => {
          await AsyncStorage.removeItem("isLoggedIn");
          router.replace("/login");
        },
      },
    ]);
  };

  const handleActionAlert = (title: string, message: string) => {
    Alert.alert(title, message, [{ text: "OK" }]);
  };

  // Direct Phone Storage Download Function with Dummy Data & Safe File Writing
  // Direct Phone Storage Download Function with Dummy Data & Safe File Writing
  const generateAndDownloadPDF = async () => {
    setIsGenerating(true);
    try {
      let reportTitle = "";
      let htmlContent = "";

      const pdfHeaderStyle = `
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 30px; color: #1E293B; background-color: #FFFFFF; }
          .header { border-bottom: 2px solid #2563EB; padding-bottom: 15px; margin-bottom: 20px; }
          .title { color: #2563EB; font-size: 22px; margin: 0; font-weight: bold; }
          .subtitle { color: #64748B; font-size: 14px; margin-top: 5px; }
          .meta { background: #F8FAFC; padding: 12px; border-radius: 8px; margin-bottom: 20px; font-size: 13px; border: 1px solid #E2E8F0; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          th { background: #2563EB; color: #FFFFFF; text-align: left; padding: 10px; font-weight: 600; }
          td { border-bottom: 1px solid #E2E8F0; padding: 10px; color: #334155; }
          tr:nth-child(even) { background-color: #F8FAFC; }
          .status-paid { color: #10B981; font-weight: bold; }
          .status-pending { color: #EF4444; font-weight: bold; }
          .footer { margin-top: 30px; font-size: 12px; text-align: right; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 10px; }
        </style>
      `;

      if (selectedReportType === "rent") {
        reportTitle = `Monthly Rent Collection Report`;
        htmlContent = `
          <html>
            <head>${pdfHeaderStyle}</head>
            <body>
              <div class="header">
                <div class="title">${selectedBranch}</div>
                <div class="subtitle">${reportTitle} — ${selectedMonth}</div>
              </div>
              <div class="meta">
                <b>Generated By:</b> Kunal Mistry (Admin)<br/>
                <b>Total Rooms Managed:</b> 24 | <b>Occupancy:</b> 92%
              </div>
              <table>
                <tr>
                  <th>Tenant Name</th>
                  <th>Room No</th>
                  <th>Rent Amount</th>
                  <th>Payment Status</th>
                </tr>
                <tr>
                  <td>Rahul Sharma</td>
                  <td>101-A</td>
                  <td>₹6,500</td>
                  <td><span class="status-paid">PAID</span></td>
                </tr>
                <tr>
                  <td>Aman Patel</td>
                  <td>102-B</td>
                  <td>₹7,000</td>
                  <td><span class="status-pending">PENDING</span></td>
                </tr>
              </table>
              <div class="footer">Kunal PG Management System • Page 1 of 1</div>
            </body>
          </html>
        `;
      } else if (selectedReportType === "expense") {
        reportTitle = `Utility & Expense Statement`;
        htmlContent = `
          <html>
            <head>${pdfHeaderStyle}</head>
            <body>
              <div class="header">
                <div class="title">${selectedBranch}</div>
                <div class="subtitle">${reportTitle} — ${selectedMonth}</div>
              </div>
              <div class="meta">
                <b>Generated By:</b> Kunal Mistry (Admin)<br/>
                <b>Category:</b> Utility Bills & Maintenance Expenses
              </div>
              <table>
                <tr>
                  <th>Expense Category</th>
                  <th>Description / Vendor</th>
                  <th>Amount</th>
                </tr>
                <tr>
                  <td>Electricity Bill</td>
                  <td>MSEB Power Board (${selectedMonth})</td>
                  <td>₹12,400</td>
                </tr>
              </table>
              <div class="footer">Kunal PG Management System • Page 1 of 1</div>
            </body>
          </html>
        `;
      } else {
        reportTitle = `Active Tenants Directory`;
        htmlContent = `
          <html>
            <head>${pdfHeaderStyle}</head>
            <body>
              <div class="header">
                <div class="title">${selectedBranch}</div>
                <div class="subtitle">${reportTitle} — ${selectedMonth}</div>
              </div>
              <div class="meta">
                <b>Generated By:</b> Kunal Mistry (Admin)<br/>
                <b>Total Occupants:</b> Active Listings Listed Below
              </div>
              <table>
                <tr>
                  <th>Tenant Name</th>
                  <th>Room No</th>
                  <th>Contact Number</th>
                </tr>
                <tr>
                  <td>Rahul Sharma</td>
                  <td>101-A</td>
                  <td>+91 98765 43210</td>
                </tr>
              </table>
              <div class="footer">Kunal PG Management System • Page 1 of 1</div>
            </body>
          </html>
        `;
      }

      // 1. Generate PDF file via expo-print
      const file = await Print.printToFileAsync({ html: htmlContent });

      if (!file || !file.uri) {
        throw new Error("PDF generation returned an invalid URI.");
      }

      // 2. Setup destination file path
      const fileName = `PG_Report_${selectedMonth.replace(/\s+/g, "_")}.pdf`;
      const documentDirectory = FileSystem.documentDirectory;

      if (!documentDirectory) {
        throw new Error("Document directory is not available on this device.");
      }

      const targetUri = `${documentDirectory}${fileName}`;

      // 3. Clear existing file if any
      const fileInfo = await FileSystem.getInfoAsync(targetUri);
      if (fileInfo.exists) {
        await FileSystem.deleteAsync(targetUri, { idempotent: true });
      }

      // 4. Move to permanent location
      await FileSystem.moveAsync({
        from: file.uri,
        to: targetUri,
      });

      setIsGenerating(false);
      setIsReportModalVisible(false);

      // 5. Open Sharing Dialog directly using targetUri
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(targetUri, {
          mimeType: "application/pdf",
          dialogTitle: "Save or Share Report PDF",
          UTI: "com.adobe.pdf",
        });
      } else {
        Alert.alert(
          "Download Successful 🎉",
          `File successfully saved at:\n${targetUri}`,
        );
      }
    } catch (error: any) {
      setIsGenerating(false);
      console.error("PDF Generation Error:", error);
      Alert.alert(
        "Error",
        `Failed to generate and save report PDF: ${error?.message || "Unknown error"}`,
      );
    }
  };
  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" backgroundColor="#0F172A" />
      <ScrollView
        style={styles.container}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 40 }}
      >
        <Text style={styles.screenTitle}>Admin Account</Text>

        {/* Profile Card */}
        <View style={styles.profileCard}>
          <View style={styles.avatar}>
            <Text style={styles.avatarText}>K</Text>
          </View>
          <Text style={styles.name}>Kunal Mistry</Text>
          <Text style={styles.role}>PG Owner & Administrator</Text>
          <Text style={styles.pg}>Kunal PG • Ahmedabad</Text>
        </View>

        {/* Core Directory */}
        <Text style={styles.sectionHeading}>Core Directory</Text>

        <TouchableOpacity
          style={styles.menuItem}
          onPress={() => router.push("/tenants" as any)}
        >
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(16, 185, 129, 0.12)" },
              ]}
            >
              <Ionicons name="people-outline" size={16} color="#10B981" />
            </View>
            <Text style={styles.menuText}>Tenants Directory</Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color="#64748B" />
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.menuItem}
          onPress={() => router.push("/rent" as any)}
        >
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(245, 158, 11, 0.12)" },
              ]}
            >
              <Ionicons name="wallet-outline" size={16} color="#F59E0B" />
            </View>
            <Text style={styles.menuText}>Rent & Ledger Records</Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color="#64748B" />
        </TouchableOpacity>

        {/* Advanced Admin Controls */}
        <Text style={styles.sectionHeading}>Advanced Admin Controls</Text>

        <TouchableOpacity
          style={styles.menuItem}
          onPress={() => setIsReportModalVisible(true)}
        >
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(14, 165, 233, 0.12)" },
              ]}
            >
              <Ionicons
                name="document-text-outline"
                size={16}
                color="#0EA5E9"
              />
            </View>
            <Text style={styles.menuText}>Export Custom Report (PDF)</Text>
          </View>
          <Ionicons name="download-outline" size={16} color="#0EA5E9" />
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.menuItem}
          onPress={() =>
            handleActionAlert("Notice Board", "Broadcast panel opened.")
          }
        >
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(236, 72, 153, 0.12)" },
              ]}
            >
              <Ionicons name="megaphone-outline" size={16} color="#EC4899" />
            </View>
            <Text style={styles.menuText}>Broadcast Notice Board</Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color="#64748B" />
        </TouchableOpacity>

        {/* Preferences */}
        <Text style={styles.sectionHeading}>Preferences</Text>

        <TouchableOpacity style={styles.menuItem}>
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(100, 116, 139, 0.12)" },
              ]}
            >
              <Ionicons name="settings-outline" size={16} color="#94A3B8" />
            </View>
            <Text style={styles.menuText}>App Settings</Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color="#64748B" />
        </TouchableOpacity>

        {/* Logout Option */}
        <TouchableOpacity
          onPress={logout}
          style={styles.logoutItem}
          activeOpacity={0.7}
        >
          <View style={styles.menuLeft}>
            <View
              style={[
                styles.iconBg,
                { backgroundColor: "rgba(239, 68, 68, 0.12)" },
              ]}
            >
              <Ionicons name="log-out-outline" size={16} color="#EF4444" />
            </View>
            <Text style={styles.logoutText}>Logout Account</Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color="#EF4444" />
        </TouchableOpacity>
      </ScrollView>

      {/* Advanced Filter & Report Download Modal */}
      <Modal
        visible={isReportModalVisible}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setIsReportModalVisible(false)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContainer}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Download Filtered Report</Text>
              <TouchableOpacity onPress={() => setIsReportModalVisible(false)}>
                <Ionicons name="close" size={20} color="#94A3B8" />
              </TouchableOpacity>
            </View>

            <ScrollView
              showsVerticalScrollIndicator={false}
              contentContainerStyle={{ paddingBottom: 20 }}
            >
              {/* 1. Select PG Branch */}
              <Text style={styles.filterLabel}>Select Property / Branch</Text>
              <View style={styles.filterRow}>
                {branchList.map((branch) => (
                  <TouchableOpacity
                    key={branch}
                    style={[
                      styles.chip,
                      selectedBranch === branch && styles.activeChip,
                    ]}
                    onPress={() => setSelectedBranch(branch)}
                  >
                    <Text
                      style={[
                        styles.chipText,
                        selectedBranch === branch && styles.activeChipText,
                      ]}
                    >
                      {branch}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>

              {/* 2. Select Month */}
              <Text style={styles.filterLabel}>Select Month</Text>
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                style={{ marginBottom: 14 }}
              >
                <View style={{ flexDirection: "row", gap: 8 }}>
                  {monthsList.map((mon) => (
                    <TouchableOpacity
                      key={mon}
                      style={[
                        styles.chip,
                        selectedMonth === mon && styles.activeChip,
                      ]}
                      onPress={() => setSelectedMonth(mon)}
                    >
                      <Text
                        style={[
                          styles.chipText,
                          selectedMonth === mon && styles.activeChipText,
                        ]}
                      >
                        {mon}
                      </Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </ScrollView>

              {/* 3. Select Report Type */}
              <Text style={styles.filterLabel}>Report Category</Text>
              <TouchableOpacity
                style={[
                  styles.reportOptionCard,
                  selectedReportType === "rent" && styles.selectedReportOption,
                ]}
                onPress={() => setSelectedReportType("rent")}
              >
                <Ionicons name="wallet" size={18} color="#F59E0B" />
                <View style={{ flex: 1, marginLeft: 10 }}>
                  <Text style={styles.reportOptTitle}>
                    Rent Collection Report
                  </Text>
                </View>
              </TouchableOpacity>

              <TouchableOpacity
                style={[
                  styles.reportOptionCard,
                  selectedReportType === "expense" &&
                    styles.selectedReportOption,
                ]}
                onPress={() => setSelectedReportType("expense")}
              >
                <Ionicons name="flash" size={18} color="#0EA5E9" />
                <View style={{ flex: 1, marginLeft: 10 }}>
                  <Text style={styles.reportOptTitle}>
                    Utility & Expense Statement
                  </Text>
                </View>
              </TouchableOpacity>

              <TouchableOpacity
                style={[
                  styles.reportOptionCard,
                  selectedReportType === "tenants" &&
                    styles.selectedReportOption,
                ]}
                onPress={() => setSelectedReportType("tenants")}
              >
                <Ionicons name="people" size={18} color="#10B981" />
                <View style={{ flex: 1, marginLeft: 10 }}>
                  <Text style={styles.reportOptTitle}>
                    Active Tenants Directory
                  </Text>
                </View>
              </TouchableOpacity>

              {/* Download Button */}
              <TouchableOpacity
                style={styles.downloadBtn}
                onPress={generateAndDownloadPDF}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <ActivityIndicator color="#FFFFFF" size="small" />
                ) : (
                  <>
                    <Ionicons
                      name="download-outline"
                      size={18}
                      color="#FFFFFF"
                    />
                    <Text style={styles.downloadBtnText}>
                      Download PDF for {selectedMonth}
                    </Text>
                  </>
                )}
              </TouchableOpacity>
            </ScrollView>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0F172A" },
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 15 },
  screenTitle: {
    color: "#F8FAFC",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 15,
  },
  profileCard: {
    backgroundColor: "#1E293B",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#334155",
  },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#2563EB",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "#3B82F6",
  },
  avatarText: { color: "#FFFFFF", fontSize: 26, fontWeight: "bold" },
  name: { color: "#FFFFFF", fontSize: 18, fontWeight: "700" },
  role: { color: "#94A3B8", fontSize: 12, marginTop: 2 },
  pg: { color: "#64748B", fontSize: 11, marginTop: 2 },
  sectionHeading: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 8,
    marginTop: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  menuItem: {
    backgroundColor: "#1E293B",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#334155",
  },
  logoutItem: {
    backgroundColor: "rgba(239, 68, 68, 0.05)",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.2)",
  },
  menuLeft: { flexDirection: "row", alignItems: "center" },
  iconBg: {
    width: 30,
    height: 30,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  menuText: { color: "#F1F5F9", fontSize: 14, fontWeight: "500" },
  logoutText: { color: "#EF4444", fontWeight: "600", fontSize: 14 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.85)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#1E293B",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#334155",
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  modalTitle: { color: "#F8FAFC", fontSize: 18, fontWeight: "700" },
  filterLabel: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 8,
    marginTop: 10,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 6,
  },
  chip: {
    backgroundColor: "#0F172A",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#334155",
  },
  activeChip: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderColor: "#3B82F6",
  },
  chipText: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
  activeChipText: { color: "#3B82F6", fontWeight: "700" },
  reportOptionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F172A",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#334155",
  },
  selectedReportOption: {
    borderColor: "#3B82F6",
    backgroundColor: "rgba(25, 103, 228, 0.1)",
  },
  reportOptTitle: { color: "#F8FAFC", fontSize: 13, fontWeight: "600" },
  downloadBtn: {
    backgroundColor: "#2563EB",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 16,
    gap: 8,
  },
  downloadBtnText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
});
